PostgreSQL VM autovaccum off
redhat-performance/benchmark-runner pull request #502
Opened 2022-12-15 14:27 UTC by ebattat

Fixes:

autovaccum off in PostgreSQL VM, depend on benchmark-operator [PR](https://github.com/cloud-bulldozer/benchmark-operator/pull/801)

2022-12-15 15:02 UTC, RobertKrawitz requested changes
Noting that benchmark-operator v1.0.2 contains the needed fix.

- Various workflow files still reference either v1.0.1 or no version at all.
- HOW_TO, README, docs/source/develop.md, and docs/source.podman.md also do not reference a version.
- benchmark_runner/common/template_operations/templates/common.yaml should either reference a fixed version of metrics.yaml or that file should be carried here.

`git grep cloud-bulldozer/benchmark-operator` should help find what needs to be fixed.

2022-12-15 15:44 UTC, ebattat commented
@RobertKrawitz 
See my answer below:

Various workflow files still reference either v1.0.1 or no version at all.
=> I dont think so because this tag generated for us.

HOW_TO, README, docs/source/develop.md, and docs/source.podman.md also do not reference a version.
=> no need add reference to benchmark-operator version because its integrated inside benchmark-runner container, same as we dont need to mention clusterbuster version.

benchmark_runner/common/template_operations/templates/common.yaml should either reference a fixed version of metrics.yaml or that file should be carried here.
=> I think it should be on separate PR

2022-12-15 16:14 UTC, RobertKrawitz commented
> @RobertKrawitz See my answer below:
> 
> Various workflow files still reference either v1.0.1 or no version at all. => All workflows are using the same version, BTW v1.0.2 version generate to us.

Why should that be referencing a different version, then?

> HOW_TO, README, docs/source/develop.md, and docs/source.podman.md also do not reference a version. => no need add reference to benchmark-operator version because its integrated inside benchmark-runner container, same as we dont need to mention clusterbuster version.

I think it should reference the same version; if there are incompatible changes in benchmark-operator, that might cause difficulties.

> benchmark_runner/common/template_operations/templates/common.yaml should either reference a fixed version of metrics.yaml or that file should be carried here. => I think it should be on separate PR

That's fine.

2022-12-15 16:25 UTC, ebattat commented
@RobertKrawitz,

Various workflow files still reference either v1.0.1 or no version at all. => All workflows are using the same version, BTW v1.0.2 version generate to us.

Why should that be referencing a different version, then?

**I have pushed autovacuum = off fix into benchmark-operator and then ask to tag it, see [PR](https://github.com/cloud-bulldozer/benchmark-operator/pull/801)**

HOW_TO, README, docs/source/develop.md, and docs/source.podman.md also do not reference a version. => no need add reference to benchmark-operator version because its integrated inside benchmark-runner container, same as we dont need to mention clusterbuster version.

I think it should reference the same version; if there are incompatible changes in benchmark-operator, that might cause difficulties.

**The best practice is to package it and add it to the dependency in setup.py, but if there is no option to the solution is to containerized it.**

benchmark_runner/common/template_operations/templates/common.yaml should either reference a fixed version of metrics.yaml or that file should be carried here. => I think it should be on separate PR

That's fine.

2022-12-20 18:56 UTC, RobertKrawitz requested changes
The doc (HOW_TO.md, README.md, docs/source/develop.md, docs/source/podman.md) should specify the explicit version, in case further development in benchmark-operator breaks us.  Otherwise, I believe it's set.

2022-12-20 19:11 UTC, RobertKrawitz approved these changes

2022-12-25 21:45 UTC, merged