clusterbuster solve permission issues
redhat-performance/benchmark-runner pull request #555
Opened 2023-02-23 18:13 UTC by ebattat

Fixes:

Solve clusterbuster pod permission issues due to ocp 4.13 PSA
More details in [PR](https://github.com/RobertKrawitz/OpenShift4-tools/pull/117)

2023-02-23 18:50 UTC, RobertKrawitz commented
This PR is premature.  It should be redone when I release the appropriate version of ClusterBuster.

2023-02-23 19:11 UTC, RobertKrawitz requested changes

2023-02-23 19:11 UTC, RobertKrawitz commented on Dockerfile
> +RUN git clone -b v1.2-kata-ci https://github.com/RobertKrawitz/OpenShift4-tools /tmp/OpenShift4-tools \
The tag will be v1.2.0-rc.0-kata-ci.

2023-02-24 06:53 UTC, ebattat commented on Dockerfile
> +RUN git clone -b v1.2-kata-ci https://github.com/RobertKrawitz/OpenShift4-tools /tmp/OpenShift4-tools \
@RobertKrawitz, why we need rc.1 ?

2023-02-25 11:34 UTC, merged