Check if Kata/ CNV operators are installed
redhat-performance/benchmark-runner pull request #638
Opened 2023-08-03 07:06 UTC by ebattat

Enhancement:
When running workloads, we are adding Kata/CNV operator verification. If the operator is not installed, an error will be raised. However, this will allow us to run the rest of the workloads even if one of the operators is not installed.

2023-08-03 17:37 UTC, RobertKrawitz requested changes
All comment cleanup, nothing substantive.

2023-08-03 17:37 UTC, RobertKrawitz commented on benchmark_runner/benchmark_operator/benchmark_operator_exceptions.py
> +        self.message = f"{workload} is required CNV operator"
"requires CNV to be installed"

2023-08-03 17:37 UTC, RobertKrawitz commented on benchmark_runner/benchmark_operator/benchmark_operator_exceptions.py
> +        self.message = f"{workload} is required Kata operator"
"requires Kata to be installed"

2023-08-03 17:37 UTC, RobertKrawitz commented on benchmark_runner/benchmark_operator/benchmark_operator_workloads_operations.py
> +        This method logins to the cluster
"logs in"

2023-08-03 17:37 UTC, RobertKrawitz commented on benchmark_runner/benchmark_operator/benchmark_operator_workloads_operations.py
> +        This method compresses tar.gz log path and returns the tar.gz path
compresses the log file and returns the compressed path.

2023-08-03 17:37 UTC, RobertKrawitz commented on benchmark_runner/common/oc/oc.py
> +        This method logins to the cluster
logs in

2023-08-03 17:37 UTC, RobertKrawitz commented on benchmark_runner/common/oc/oc.py
> +        This method gets pods
retrieves information on benchmark-runner pods in `oc get pod` format.

2023-08-03 17:37 UTC, RobertKrawitz commented on benchmark_runner/common/oc/oc.py
> +        This method execs a command and return the answer
execs a command within a specified pod and optional container and returns the output

2023-08-03 17:37 UTC, RobertKrawitz commented on benchmark_runner/common/oc/oc.py
> +        This method waits to pod to be completed
waits for a pod to be completed

2023-08-03 17:37 UTC, RobertKrawitz commented on benchmark_runner/workloads/workloads_operations.py
> +        This method compresses tar.gz log path and returns the tar.gz path
compresses the log file and returns the compressed path

2023-08-03 17:37 UTC, RobertKrawitz commented on benchmark_runner/workloads/workloads_operations.py
> +        This method returns metadata. The 'kind' arguments is optional.
returns metadata for a run, optionally filtered by runtime kind

2023-08-04 17:49 UTC, RobertKrawitz requested changes
A few more minor comment issues

2023-08-04 17:49 UTC, RobertKrawitz commented on benchmark_runner/benchmark_operator/benchmark_operator_workloads_operations.py
> +        This method makes deploy benchmark operator
"This method deploys the benchmark operator"

2023-08-04 17:49 UTC, RobertKrawitz commented on benchmark_runner/benchmark_operator/benchmark_operator_workloads_operations.py
> +        This method makes undeploy benchmark operator
"This method removes a benchmark-operator deployment"

2023-08-04 17:49 UTC, RobertKrawitz commented on benchmark_runner/benchmark_operator/benchmark_operator_workloads_operations.py
> +        This method makes undeploy benchmark controller manager if exist
"uninstalls/undeploys/removes benchmark controller manager, if it exists"

2023-08-04 17:49 UTC, RobertKrawitz commented on benchmark_runner/common/oc/oc.py
> +        This method logins to the cluster
"logs in"

2023-08-04 18:05 UTC, ebattat commented
Thx, Please let me know if there are more issues

2023-08-04 19:30 UTC, RobertKrawitz approved these changes

2023-08-06 04:15 UTC, merged