update Grafana dashboard into folder
redhat-performance/benchmark-runner pull request #655
Opened 2023-09-10 15:13 UTC by ebattat

## Type of change
Note: Fill **x** in []
- [ ] bug
- [x] enhancement
- [ ] documentation
- [ ] dependencies

## Description

For keeping dashboard organized, update Grafana dashboard into dedicate folder instead of General folder

## For security reasons, all pull requests need to be approved first before running any automated CI

2023-09-11 14:33 UTC, RobertKrawitz requested changes
Trivial changes

2023-09-11 14:33 UTC, RobertKrawitz commented on .github/workflows/Nightly_Perf_Env_CI.yml
> +      - name: Commit main.libsonnet if any products versions are detected
"changes to product versions"

2023-09-11 14:33 UTC, RobertKrawitz commented on .github/workflows/Perf_Env_Build_Test_CI.yml
> +      - name: Commit main.libsonnet if any products versions are detected
"changes to product versions"

2023-09-11 16:18 UTC, ebattat commented on benchmark_runner/common/grafana/grafana_operations.py
> +        This method get dashboard folder id
Update more clear document

2023-09-12 16:22 UTC, RobertKrawitz approved these changes

2023-09-13 08:06 UTC, merged